apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-web
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.web.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}-web
    app.kubernetes.io/instance: {{ .Release.Name }}
