"""Procore integration API endpoints.

Handles OAuth connection flow and Procore data access.
"""

from __future__ import annotations

import logging
import uuid

from fastapi import APIRouter, Depends, HTTPException, Query, status
from fastapi.responses import RedirectResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.dependencies import get_current_user, require_permission, verify_project_access
from app.models.user import User

logger = logging.getLogger(__name__)

router = APIRouter()


# ---------------------------------------------------------------------------
# OAuth flow
# ---------------------------------------------------------------------------


@router.get("/connect")
async def procore_connect(
    current_user: User = Depends(require_permission("procurement", "create")),
):
    """Initiate Procore OAuth flow.

    Generates an authorization URL and redirects the user's browser to
    Procore's login page. After the user grants access, Procore redirects
    back to /callback with an authorization code.
    """
    from app.services.integrations.procore_oauth import (
        ProcoreOAuthError,
        generate_auth_url,
    )

    try:
        auth_url = await generate_auth_url(current_user.id, current_user.org_id)
        return RedirectResponse(url=auth_url, status_code=status.HTTP_302_FOUND)
    except ProcoreOAuthError as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(exc),
        ) from exc


@router.get("/callback")
async def procore_callback(
    code: str = Query(
        ..., min_length=1, max_length=512, description="Authorization code from Procore"
    ),
    state: str = Query(..., min_length=1, max_length=512, description="CSRF state token"),
    db: AsyncSession = Depends(get_db),
):
    """Handle Procore OAuth callback.

    SECURITY (C-05): This endpoint is intentionally not protected by
    ``get_current_user`` because it is invoked via browser redirect from
    Procore's authorization server.  Security relies on:

    1. The ``state`` parameter is a cryptographic token generated by
       ``generate_auth_url()`` and stored server-side with the originating
       ``user_id`` and ``org_id``.  ``exchange_code()`` validates the state
       against the stored value and rejects replays (single-use).
    2. The authorization ``code`` is only valid for a short window and
       can only be exchanged once.
    3. We do not return sensitive tokens in the response — only
       connection status metadata.

    Returns a success message (in production, redirect to the frontend).
    """
    from app.services.integrations.procore_oauth import (
        ProcoreOAuthError,
        exchange_code,
    )

    try:
        conn = await exchange_code(code=code, state=state, db=db)

        # Auto-register webhooks for real-time updates
        webhook_result = None
        if conn.procore_company_id:
            try:
                from app.services.integrations.procore_webhooks import (
                    register_webhooks,
                )

                webhook_result = await register_webhooks(
                    org_id=conn.organization_id,
                    company_id=int(conn.procore_company_id),
                    db=db,
                )
            except Exception as wh_exc:
                logger.warning("Webhook registration failed: %s", wh_exc)

        logger.info(
            "Procore OAuth callback completed for org %s",
            conn.organization_id,
        )

        return {
            "status": "connected",
            "organization_id": str(conn.organization_id),
            "connected_at": conn.connected_at.isoformat() if conn.connected_at else None,
            "message": "Procore connection established successfully.",
            "webhooks": webhook_result,
        }
    except ProcoreOAuthError as exc:
        logger.warning("Procore OAuth callback failed: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(exc),
        ) from exc


@router.get("/status")
async def procore_status(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Get the current Procore connection status for the user's organization."""
    from app.services.integrations.procore_oauth import get_connection_status

    result = await get_connection_status(current_user.org_id, db)
    if result is None:
        return {"connected": False}
    return result


@router.post("/disconnect")
async def procore_disconnect(
    current_user: User = Depends(require_permission("procurement", "delete")),
    db: AsyncSession = Depends(get_db),
):
    """Disconnect Procore integration for the user's organization.

    Removes stored OAuth tokens from the database.
    """
    from app.services.integrations.procore_oauth import disconnect_procore

    removed = await disconnect_procore(current_user.org_id, db)
    if not removed:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No Procore connection found for this organization.",
        )
    return {"status": "disconnected", "message": "Procore connection removed."}


# ---------------------------------------------------------------------------
# Procore data endpoints
# ---------------------------------------------------------------------------


@router.get("/companies")
async def list_procore_companies(
    current_user: User = Depends(require_permission("procurement", "read")),
    db: AsyncSession = Depends(get_db),
):
    """List Procore companies accessible to the connected account."""
    from app.services.integrations.procore_api import ProcoreAPI
    from app.services.integrations.procore_oauth import ProcoreOAuthError

    try:
        api = ProcoreAPI(org_id=current_user.org_id, db=db)
        companies = await api.list_companies()
        return {"companies": [c.model_dump() for c in companies]}
    except ProcoreOAuthError as exc:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=str(exc),
        ) from exc


@router.get("/projects")
async def list_procore_projects(
    company_id: int = Query(..., description="Procore company ID"),
    current_user: User = Depends(require_permission("procurement", "read")),
    db: AsyncSession = Depends(get_db),
):
    """List projects for a Procore company."""
    from app.services.integrations.procore_api import ProcoreAPI
    from app.services.integrations.procore_oauth import ProcoreOAuthError

    try:
        api = ProcoreAPI(org_id=current_user.org_id, db=db)
        projects = await api.list_projects(company_id)
        return {"projects": [p.model_dump() for p in projects]}
    except ProcoreOAuthError as exc:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=str(exc),
        ) from exc


# ---------------------------------------------------------------------------
# Sync endpoints
# ---------------------------------------------------------------------------


@router.post("/sync")
async def trigger_full_sync(
    current_user: User = Depends(require_permission("procurement", "create")),
    db: AsyncSession = Depends(get_db),
):
    """Trigger a full Procore data sync for the user's organization.

    Creates a SyncLog entry and syncs all projects and their entities
    (RFIs, documents, change orders, budget, daily logs).
    """
    from app.models.sync_log import SyncLog
    from app.services.integrations.procore_oauth import get_connection_status
    from app.services.integrations.procore_sync import sync_all

    # Check connection exists
    conn_status = await get_connection_status(current_user.org_id, db)
    if not conn_status or not conn_status.get("connected"):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No active Procore connection. Connect first via /integrations/procore/connect.",
        )

    # Check for already-running sync
    from sqlalchemy import select as sa_select

    running = await db.execute(
        sa_select(SyncLog).where(
            SyncLog.org_id == current_user.org_id,
            SyncLog.status == "running",
        )
    )
    if running.scalar_one_or_none():
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="A sync is already in progress for this organization.",
        )

    # Run sync
    sync_log = await sync_all(
        db=db,
        org_id=current_user.org_id,
        triggered_by=current_user.id,
    )

    return {
        "sync_id": str(sync_log.id),
        "status": sync_log.status,
        "entities_synced": sync_log.entities_synced,
        "error_count": len(sync_log.errors) if sync_log.errors else 0,
    }


@router.get("/sync/status")
async def get_sync_status(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Get the latest sync status for the user's organization."""
    from sqlalchemy import select as sa_select

    from app.models.sync_log import SyncLog

    result = await db.execute(
        sa_select(SyncLog)
        .where(SyncLog.org_id == current_user.org_id)
        .order_by(SyncLog.started_at.desc())
        .limit(1)
    )
    sync_log = result.scalar_one_or_none()

    if sync_log is None:
        return {"has_synced": False, "message": "No sync history found."}

    return {
        "has_synced": True,
        "sync_id": str(sync_log.id),
        "sync_type": sync_log.sync_type,
        "status": sync_log.status,
        "started_at": sync_log.started_at.isoformat() if sync_log.started_at else None,
        "completed_at": sync_log.completed_at.isoformat() if sync_log.completed_at else None,
        "entities_synced": sync_log.entities_synced,
        "error_count": len(sync_log.errors) if sync_log.errors else 0,
        "errors": sync_log.errors[:10] if sync_log.errors else [],
    }


@router.post("/sync/{project_id}")
async def trigger_project_sync(
    project_id: uuid.UUID,
    current_user: User = Depends(require_permission("procurement", "create")),
    db: AsyncSession = Depends(get_db),
):
    """Trigger a Procore data sync for a single project.

    The project must already exist with a procore_id (previously synced).
    """
    await verify_project_access(project_id, current_user, db)

    from sqlalchemy import select as sa_select

    from app.models.procore_connection import ProcoreConnection
    from app.models.project import Project
    from app.services.integrations.procore_sync import sync_project_data

    # Load project record (access already verified above)
    result = await db.execute(
        sa_select(Project).where(
            Project.id == project_id,
            Project.org_id == current_user.org_id,
        )
    )
    project = result.scalar_one_or_none()
    if not project:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Project not found.",
        )

    if not project.procore_id:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="This project is not linked to Procore. Run a full sync first.",
        )

    # Get company_id from connection
    conn_result = await db.execute(
        sa_select(ProcoreConnection).where(ProcoreConnection.organization_id == current_user.org_id)
    )
    conn = conn_result.scalar_one_or_none()
    if not conn or not conn.procore_company_id:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No Procore connection found.",
        )

    sync_result = await sync_project_data(
        db=db,
        org_id=current_user.org_id,
        project_id=project.id,
        procore_project_id=project.procore_id,
        company_id=int(conn.procore_company_id),
    )

    return {
        "status": "completed" if not sync_result["errors"] else "partial",
        "project_id": project_id,
        "entities_synced": sync_result["entities_synced"],
        "error_count": len(sync_result["errors"]),
    }
