-- ============================================================================
-- FIX MISSING COLUMNS: Model-to-DB Mismatch Resolution
-- ============================================================================
-- Generated by cross-referencing SQLAlchemy model definitions against
-- Alembic migration history. Each section documents which model defines
-- the column and which migration SHOULD have created it but didn't.
--
-- Safe to run multiple times (uses ADD COLUMN IF NOT EXISTS).
-- Execute against the constructai database.
-- ============================================================================

BEGIN;

-- ============================================================================
-- 1. safety_alerts — missing: updated_at
-- ============================================================================
-- Model: app/models/safety_incident.py  SafetyAlert.updated_at
-- Migration 004 creates safety_alerts but does NOT include updated_at.
-- The model defines it with server_default=func.now(), onupdate=func.now().
-- This is the reported error: "safety_alerts.updated_at does not exist"
-- Seed file: demo/seed/seed_safety.py (SafetyAlert)

ALTER TABLE safety_alerts
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();


-- ============================================================================
-- 2. safety_alerts — missing: is_acknowledged index column already exists,
--    but verify the column has the index flag the model expects.
--    (No action needed — column exists in migration 004.)
-- ============================================================================


-- ============================================================================
-- 3. compliance_checks — missing: updated_at
-- ============================================================================
-- Model: app/models/quality.py  ComplianceCheck has NO updated_at
--   (only created_at). But looking more carefully at the model, the
--   ComplianceCheck model does NOT define updated_at. So this is fine.
--   Migration 005 also does not create updated_at for compliance_checks.
-- NO ACTION NEEDED.


-- ============================================================================
-- 4. projects — missing: data_source, procore_id
-- ============================================================================
-- Model: app/models/project.py defines data_source and procore_id.
-- Migration 001 creates projects WITHOUT these columns.
-- Migration 011 adds them. If migrations ran through 011, these exist.
-- Including defensively in case migrations were partially applied.

ALTER TABLE projects
    ADD COLUMN IF NOT EXISTS data_source TEXT NOT NULL DEFAULT 'manual';

ALTER TABLE projects
    ADD COLUMN IF NOT EXISTS procore_id BIGINT;


-- ============================================================================
-- 5. documents — missing: data_source, procore_id
-- ============================================================================
-- Model: app/models/document.py defines data_source and procore_id.
-- Migration 002 creates documents WITHOUT these columns.
-- Migration 011 adds them.

ALTER TABLE documents
    ADD COLUMN IF NOT EXISTS data_source TEXT NOT NULL DEFAULT 'manual';

ALTER TABLE documents
    ADD COLUMN IF NOT EXISTS procore_id BIGINT;


-- ============================================================================
-- 6. rfis — missing: data_source, procore_id, and RFI workflow fields
-- ============================================================================
-- Model: app/models/communication.py RFI defines many fields added by
-- migrations 011 (data_source, procore_id) and 016 (workflow fields).

ALTER TABLE rfis
    ADD COLUMN IF NOT EXISTS data_source TEXT NOT NULL DEFAULT 'manual';

ALTER TABLE rfis
    ADD COLUMN IF NOT EXISTS procore_id BIGINT;

-- RFI workflow fields (migration 016)
ALTER TABLE rfis
    ADD COLUMN IF NOT EXISTS answer TEXT;

ALTER TABLE rfis
    ADD COLUMN IF NOT EXISTS ball_in_court UUID;

ALTER TABLE rfis
    ADD COLUMN IF NOT EXISTS cost_impact BOOLEAN;

ALTER TABLE rfis
    ADD COLUMN IF NOT EXISTS schedule_impact BOOLEAN;

ALTER TABLE rfis
    ADD COLUMN IF NOT EXISTS cost_impact_amount NUMERIC(14, 2);

ALTER TABLE rfis
    ADD COLUMN IF NOT EXISTS schedule_impact_days INTEGER;

ALTER TABLE rfis
    ADD COLUMN IF NOT EXISTS spec_section TEXT;

ALTER TABLE rfis
    ADD COLUMN IF NOT EXISTS drawing_reference TEXT;

ALTER TABLE rfis
    ADD COLUMN IF NOT EXISTS distribution_list JSONB NOT NULL DEFAULT '[]';

ALTER TABLE rfis
    ADD COLUMN IF NOT EXISTS date_sent DATE;

ALTER TABLE rfis
    ADD COLUMN IF NOT EXISTS date_answered TIMESTAMPTZ;

ALTER TABLE rfis
    ADD COLUMN IF NOT EXISTS date_closed TIMESTAMPTZ;


-- ============================================================================
-- 7. change_orders — missing: data_source, procore_id, lifecycle columns
-- ============================================================================
-- Model: app/models/evm.py ChangeOrder defines columns from migrations
-- 005 (base), 011 (procore), and 019 (lifecycle).

ALTER TABLE change_orders
    ADD COLUMN IF NOT EXISTS data_source TEXT NOT NULL DEFAULT 'manual';

ALTER TABLE change_orders
    ADD COLUMN IF NOT EXISTS procore_id BIGINT;

-- Lifecycle columns (migration 019)
ALTER TABLE change_orders
    ADD COLUMN IF NOT EXISTS cor_id UUID;

ALTER TABLE change_orders
    ADD COLUMN IF NOT EXISTS approved_date TIMESTAMPTZ;

ALTER TABLE change_orders
    ADD COLUMN IF NOT EXISTS executed_date TIMESTAMPTZ;

ALTER TABLE change_orders
    ADD COLUMN IF NOT EXISTS labor_cost NUMERIC(14, 2) NOT NULL DEFAULT 0;

ALTER TABLE change_orders
    ADD COLUMN IF NOT EXISTS material_cost NUMERIC(14, 2) NOT NULL DEFAULT 0;

ALTER TABLE change_orders
    ADD COLUMN IF NOT EXISTS equipment_cost NUMERIC(14, 2) NOT NULL DEFAULT 0;

ALTER TABLE change_orders
    ADD COLUMN IF NOT EXISTS subcontractor_cost NUMERIC(14, 2) NOT NULL DEFAULT 0;

ALTER TABLE change_orders
    ADD COLUMN IF NOT EXISTS overhead_cost NUMERIC(14, 2) NOT NULL DEFAULT 0;

ALTER TABLE change_orders
    ADD COLUMN IF NOT EXISTS markup_pct NUMERIC(5, 2) NOT NULL DEFAULT 0;

ALTER TABLE change_orders
    ADD COLUMN IF NOT EXISTS overhead_pct NUMERIC(5, 2) NOT NULL DEFAULT 0;

ALTER TABLE change_orders
    ADD COLUMN IF NOT EXISTS original_contract_sum NUMERIC(16, 2);

ALTER TABLE change_orders
    ADD COLUMN IF NOT EXISTS previous_cos_sum NUMERIC(16, 2);

ALTER TABLE change_orders
    ADD COLUMN IF NOT EXISTS this_co_amount NUMERIC(16, 2);

ALTER TABLE change_orders
    ADD COLUMN IF NOT EXISTS new_contract_sum NUMERIC(16, 2);


-- ============================================================================
-- 8. daily_logs — missing: data_source, procore_id, v2 fields, v3 fields
-- ============================================================================
-- Model: app/models/productivity.py DailyLog defines columns from
-- migrations 005 (base), 011 (procore), 018 (v2), and 026 (v3).

ALTER TABLE daily_logs
    ADD COLUMN IF NOT EXISTS data_source TEXT NOT NULL DEFAULT 'manual';

ALTER TABLE daily_logs
    ADD COLUMN IF NOT EXISTS procore_id BIGINT;

-- v2 fields (migration 018)
ALTER TABLE daily_logs
    ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'draft';

ALTER TABLE daily_logs
    ADD COLUMN IF NOT EXISTS work_narrative TEXT;

ALTER TABLE daily_logs
    ADD COLUMN IF NOT EXISTS manpower_by_trade JSONB NOT NULL DEFAULT '[]';

ALTER TABLE daily_logs
    ADD COLUMN IF NOT EXISTS equipment_entries JSONB NOT NULL DEFAULT '[]';

ALTER TABLE daily_logs
    ADD COLUMN IF NOT EXISTS deliveries JSONB NOT NULL DEFAULT '[]';

ALTER TABLE daily_logs
    ADD COLUMN IF NOT EXISTS visitors JSONB NOT NULL DEFAULT '[]';

ALTER TABLE daily_logs
    ADD COLUMN IF NOT EXISTS photos JSONB NOT NULL DEFAULT '[]';

ALTER TABLE daily_logs
    ADD COLUMN IF NOT EXISTS location_lat NUMERIC(9, 6);

ALTER TABLE daily_logs
    ADD COLUMN IF NOT EXISTS location_lon NUMERIC(9, 6);

ALTER TABLE daily_logs
    ADD COLUMN IF NOT EXISTS approved_by UUID;

ALTER TABLE daily_logs
    ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ;

ALTER TABLE daily_logs
    ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMPTZ;

-- v3 fields (migration 026)
ALTER TABLE daily_logs
    ADD COLUMN IF NOT EXISTS safety_incidents TEXT;

ALTER TABLE daily_logs
    ADD COLUMN IF NOT EXISTS safety_topic_discussed TEXT;

ALTER TABLE daily_logs
    ADD COLUMN IF NOT EXISTS weather_delay_hours NUMERIC(5, 1);


-- ============================================================================
-- 9. cost_items — missing: expanded columns from migration 012
-- ============================================================================
-- Model: app/models/estimating.py CostItem defines columns from
-- migration 003 (base) and 012 (expanded).

ALTER TABLE cost_items
    ADD COLUMN IF NOT EXISTS csi_code TEXT;

ALTER TABLE cost_items
    ADD COLUMN IF NOT EXISTS material_cost NUMERIC(12, 2);

ALTER TABLE cost_items
    ADD COLUMN IF NOT EXISTS labor_cost NUMERIC(12, 2);

ALTER TABLE cost_items
    ADD COLUMN IF NOT EXISTS equipment_cost NUMERIC(12, 2);

ALTER TABLE cost_items
    ADD COLUMN IF NOT EXISTS unit_of_measure TEXT;

ALTER TABLE cost_items
    ADD COLUMN IF NOT EXISTS crew_size NUMERIC(6, 2);

ALTER TABLE cost_items
    ADD COLUMN IF NOT EXISTS daily_output NUMERIC(12, 4);

ALTER TABLE cost_items
    ADD COLUMN IF NOT EXISTS manhours_per_unit NUMERIC(10, 4);

ALTER TABLE cost_items
    ADD COLUMN IF NOT EXISTS uncertainty_min NUMERIC(5, 4);

ALTER TABLE cost_items
    ADD COLUMN IF NOT EXISTS uncertainty_max NUMERIC(5, 4);

ALTER TABLE cost_items
    ADD COLUMN IF NOT EXISTS last_updated TIMESTAMPTZ;


-- ============================================================================
-- 10. schedule_baselines — missing: import/calendar columns from migration 021
-- ============================================================================
-- Model: app/models/scheduling.py ScheduleBaseline defines columns from
-- migrations 003 (base) and 021 (import/calendar).

ALTER TABLE schedule_baselines
    ADD COLUMN IF NOT EXISTS source_file TEXT;

ALTER TABLE schedule_baselines
    ADD COLUMN IF NOT EXISTS source_format TEXT;

ALTER TABLE schedule_baselines
    ADD COLUMN IF NOT EXISTS calendars JSONB NOT NULL DEFAULT '[]';

ALTER TABLE schedule_baselines
    ADD COLUMN IF NOT EXISTS data_date DATE;


-- ============================================================================
-- 11. schedule_activities — missing: columns from migrations 021 and 029
-- ============================================================================
-- Model: app/models/scheduling.py ScheduleActivity defines columns from
-- migrations 003 (base), 021 (calendar/import), and 029 (AI progress).

ALTER TABLE schedule_activities
    ADD COLUMN IF NOT EXISTS calendar_id TEXT;

ALTER TABLE schedule_activities
    ADD COLUMN IF NOT EXISTS original_id TEXT;

ALTER TABLE schedule_activities
    ADD COLUMN IF NOT EXISTS wbs_path TEXT;

ALTER TABLE schedule_activities
    ADD COLUMN IF NOT EXISTS ai_pct_complete NUMERIC(5, 2);

ALTER TABLE schedule_activities
    ADD COLUMN IF NOT EXISTS last_photo_update TIMESTAMPTZ;


-- ============================================================================
-- 12. meeting_minutes — missing: enhanced columns from migration 020
-- ============================================================================
-- Model: app/models/communication.py MeetingMinutes defines columns from
-- migrations 005 (base) and 020 (enhanced).

ALTER TABLE meeting_minutes
    ADD COLUMN IF NOT EXISTS meeting_location TEXT;

ALTER TABLE meeting_minutes
    ADD COLUMN IF NOT EXISTS start_time TIME;

ALTER TABLE meeting_minutes
    ADD COLUMN IF NOT EXISTS end_time TIME;

ALTER TABLE meeting_minutes
    ADD COLUMN IF NOT EXISTS agenda_items JSONB NOT NULL DEFAULT '[]';

ALTER TABLE meeting_minutes
    ADD COLUMN IF NOT EXISTS notes TEXT;

ALTER TABLE meeting_minutes
    ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'draft';


-- ============================================================================
-- 13. submittals — missing: workflow columns from migration 017
-- ============================================================================
-- Model: app/models/communication.py Submittal defines columns from
-- migrations 005 (base) and 017 (workflow).

ALTER TABLE submittals
    ADD COLUMN IF NOT EXISTS description TEXT;

ALTER TABLE submittals
    ADD COLUMN IF NOT EXISTS spec_section_name TEXT;

ALTER TABLE submittals
    ADD COLUMN IF NOT EXISTS submittal_type TEXT NOT NULL DEFAULT 'other';

ALTER TABLE submittals
    ADD COLUMN IF NOT EXISTS priority TEXT NOT NULL DEFAULT 'normal';

ALTER TABLE submittals
    ADD COLUMN IF NOT EXISTS revision_number INTEGER NOT NULL DEFAULT 0;

ALTER TABLE submittals
    ADD COLUMN IF NOT EXISTS current_reviewer UUID;

ALTER TABLE submittals
    ADD COLUMN IF NOT EXISTS ball_in_court UUID;

ALTER TABLE submittals
    ADD COLUMN IF NOT EXISTS date_required DATE;

ALTER TABLE submittals
    ADD COLUMN IF NOT EXISTS date_submitted TIMESTAMPTZ;

ALTER TABLE submittals
    ADD COLUMN IF NOT EXISTS date_returned TIMESTAMPTZ;

ALTER TABLE submittals
    ADD COLUMN IF NOT EXISTS lead_time_days INTEGER;

ALTER TABLE submittals
    ADD COLUMN IF NOT EXISTS distribution_list JSONB NOT NULL DEFAULT '[]';

ALTER TABLE submittals
    ADD COLUMN IF NOT EXISTS linked_rfi_ids JSONB NOT NULL DEFAULT '[]';

ALTER TABLE submittals
    ADD COLUMN IF NOT EXISTS review_chain JSONB NOT NULL DEFAULT '[]';

ALTER TABLE submittals
    ADD COLUMN IF NOT EXISTS data_source TEXT NOT NULL DEFAULT 'manual';

ALTER TABLE submittals
    ADD COLUMN IF NOT EXISTS procore_id BIGINT;


-- ============================================================================
-- 14. ProjectMember — missing: invited_by (model has it, migration 001 does not)
-- ============================================================================
-- Model: app/models/project.py ProjectMember.invited_by
-- Migration 001 creates project_members WITHOUT invited_by.

ALTER TABLE project_members
    ADD COLUMN IF NOT EXISTS invited_by UUID;


-- ============================================================================
-- 15. ProjectMember — role default changed from 'member' to 'field_engineer'
-- ============================================================================
-- Model has server_default="field_engineer" but migration 001 has "member".
-- This only affects the default, not the column existence.
-- No ALTER needed — existing rows keep their values; new rows will use
-- whatever the DB default is (or the ORM default).


-- ============================================================================
-- INDEXES that may be missing (defensive — CREATE INDEX IF NOT EXISTS)
-- ============================================================================

-- safety_alerts.is_acknowledged index (model has index=True but migration 004
-- does not create this index)
CREATE INDEX IF NOT EXISTS idx_safety_alerts_is_acknowledged
    ON safety_alerts (is_acknowledged);

-- cost_items indexes (migration 012)
CREATE INDEX IF NOT EXISTS idx_cost_items_csi_code
    ON cost_items (csi_code);

CREATE INDEX IF NOT EXISTS idx_cost_items_data_source
    ON cost_items (data_source);

CREATE INDEX IF NOT EXISTS idx_cost_items_category_unit
    ON cost_items (category, unit);

-- daily_logs indexes (migration 018)
CREATE INDEX IF NOT EXISTS idx_daily_logs_project_date
    ON daily_logs (project_id, log_date);

CREATE INDEX IF NOT EXISTS idx_daily_logs_status
    ON daily_logs (status);


COMMIT;

-- ============================================================================
-- SUMMARY OF TABLES AFFECTED
-- ============================================================================
-- Table                   | Missing Columns                              | Source Migration
-- ----------------------- | -------------------------------------------- | ---------------
-- safety_alerts           | updated_at                                   | 004 (omitted)
-- projects                | data_source, procore_id                      | 011
-- documents               | data_source, procore_id                      | 011
-- rfis                    | data_source, procore_id, 10 workflow fields  | 011, 016
-- change_orders           | data_source, procore_id, 14 lifecycle fields | 011, 019
-- daily_logs              | data_source, procore_id, 12 v2 fields, 3 v3 | 011, 018, 026
-- cost_items              | 11 expanded DDC CWICR fields                 | 012
-- schedule_baselines      | 4 import/calendar fields                     | 021
-- schedule_activities     | 5 fields (calendar, import, AI progress)     | 021, 029
-- meeting_minutes         | 6 enhanced fields                            | 020
-- submittals              | 16 workflow fields                           | 017
-- project_members         | invited_by                                   | (never migrated)
-- ============================================================================
